[I 2024-06-19 18:32:22.515 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-06-19 18:32:22.527 ServerApp] jupyter_server_terminals | extension was successfully linked.
[W 2024-06-19 18:32:22.530 LabApp] 'kernel_spec_manager_class' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-06-19 18:32:22.532 LabApp] 'kernel_spec_manager_class' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2024-06-19 18:32:22.540 ServerApp] jupyterlab | extension was successfully linked.
[W 2024-06-19 18:32:22.543 NotebookApp] 'kernel_spec_manager_class' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2024-06-19 18:32:22.551 ServerApp] nbclassic | extension was successfully linked.
[I 2024-06-19 18:32:23.518 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-06-19 18:32:26.864 ServerApp] nb_conda_kernels | enabled, 12 kernels found.
[I 2024-06-19 18:32:27.125 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-06-19 18:32:27.130 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-06-19 18:32:27.133 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-06-19 18:32:27.137 LabApp] JupyterLab extension loaded from /home/van/miniforge3/lib/python3.10/site-packages/jupyterlab
[I 2024-06-19 18:32:27.137 LabApp] JupyterLab application directory is /home/van/miniforge3/share/jupyter/lab
[I 2024-06-19 18:32:27.138 LabApp] Extension Manager is 'pypi'.
[I 2024-06-19 18:32:27.170 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-06-19 18:32:27.183 ServerApp] nbclassic | extension was successfully loaded.
[I 2024-06-19 18:32:27.184 ServerApp] Serving notebooks from local directory: /home/van
[I 2024-06-19 18:32:27.184 ServerApp] Jupyter Server 2.14.0 is running at:
[I 2024-06-19 18:32:27.184 ServerApp] http://himem04:8988/lab?token=65b914840fb933a09b889bc72a00270bd9fd20477b73c37a
[I 2024-06-19 18:32:27.184 ServerApp]     http://127.0.0.1:8988/lab?token=65b914840fb933a09b889bc72a00270bd9fd20477b73c37a
[I 2024-06-19 18:32:27.184 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-06-19 18:32:27.193 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/van/.local/share/jupyter/runtime/jpserver-95733-open.html
    Or copy and paste one of these URLs:
        http://himem04:8988/lab?token=65b914840fb933a09b889bc72a00270bd9fd20477b73c37a
        http://127.0.0.1:8988/lab?token=65b914840fb933a09b889bc72a00270bd9fd20477b73c37a
[I 2024-06-19 18:32:27.257 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-06-19 18:32:54.085 LabApp] Could not determine jupyterlab build status without nodejs
[W 2024-06-19 18:38:22.414 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 18:38:29.620 ServerApp] Kernel started: 31aa2d3e-3e42-479d-a7df-938909f95eb4
[W 2024-06-19 18:39:29.682 ServerApp] Timeout waiting for kernel_info reply from 31aa2d3e-3e42-479d-a7df-938909f95eb4
[I 2024-06-19 18:39:29.684 ServerApp] Connecting to kernel 31aa2d3e-3e42-479d-a7df-938909f95eb4.
[W 2024-06-19 18:39:34.208 ServerApp] Nudge: attempt 10 on kernel 31aa2d3e-3e42-479d-a7df-938909f95eb4
[W 2024-06-19 18:39:39.230 ServerApp] Nudge: attempt 20 on kernel 31aa2d3e-3e42-479d-a7df-938909f95eb4
[W 2024-06-19 18:39:44.253 ServerApp] Nudge: attempt 30 on kernel 31aa2d3e-3e42-479d-a7df-938909f95eb4
Exception in callback _chain_future.<locals>._set_state(<Future finished result={}>, <Future at 0x...returned dict>) at /home/van/miniforge3/lib/python3.10/asyncio/futures.py:379
handle: <Handle _chain_future.<locals>._set_state(<Future finished result={}>, <Future at 0x...returned dict>) at /home/van/miniforge3/lib/python3.10/asyncio/futures.py:379>
Traceback (most recent call last):
  File "/home/van/miniforge3/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/van/miniforge3/lib/python3.10/asyncio/futures.py", line 381, in _set_state
    _copy_future_state(other, future)
  File "/home/van/miniforge3/lib/python3.10/asyncio/futures.py", line 351, in _copy_future_state
    assert not dest.done()
AssertionError
[I 2024-06-19 18:39:45.329 ServerApp] Connecting to kernel 31aa2d3e-3e42-479d-a7df-938909f95eb4.
[W 2024-06-19 18:39:45.389 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x2ab8b024cd60>
[I 2024-06-19 18:39:45.392 ServerApp] Connecting to kernel 31aa2d3e-3e42-479d-a7df-938909f95eb4.
[I 2024-06-19 18:40:22.619 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[W 2024-06-19 18:40:22.620 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 18:42:23.386 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[W 2024-06-19 18:42:23.388 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 18:44:23.716 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[W 2024-06-19 18:44:23.717 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[W 2024-06-19 18:45:42.708 ServerApp] delete /examplefiles/analysis/results0
[W 2024-06-19 18:45:42.711 ServerApp] 400 DELETE /api/contents/examplefiles/analysis/results0?1718840742672 (172.18.19.241): send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
[W 2024-06-19 18:45:42.712 ServerApp] wrote error: "send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783'"
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 158, in find_ext_volume_fallback_trash
        check_create(trash_dir)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 96, in check_create
        os.makedirs(dir, 0o700)
      File "/home/van/miniforge3/lib/python3.10/os.py", line 225, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 1027, in delete_file
        send2trash(os_path)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 210, in send2trash
        dest_trash = find_ext_volume_trash(topdir)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 169, in find_ext_volume_trash
        trash_dir = find_ext_volume_fallback_trash(volume_root)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 161, in find_ext_volume_fallback_trash
        raise TrashPermissionError(e.filename)
    send2trash.exceptions.TrashPermissionError: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 335, in delete
        await ensure_async(cm.delete(path))
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/manager.py", line 900, in delete
        await self.delete_file(path)
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 1029, in delete_file
        raise web.HTTPError(400, "send2trash failed: %s" % e) from e
    tornado.web.HTTPError: HTTP 400: Bad Request (send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783')
[W 2024-06-19 18:45:42.818 ServerApp] 400 DELETE /api/contents/examplefiles/analysis/results0?1718840742672 (d92171e8cafe4b9fa3bf748e2511af5c@172.18.19.241) 111.70ms referer=http://127.0.0.1:8988/lab/tree/examplefiles/analysis/mbar.ipynb
[I 2024-06-19 18:45:47.678 ServerApp] Copying examplefiles/analysis/mbar.ipynb to /examplefiles/analysis
[W 2024-06-19 18:45:47.696 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[W 2024-06-19 18:45:47.710 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[W 2024-06-19 18:45:47.712 ServerApp] Notebook examplefiles/analysis/mbar-Copy1.ipynb is not trusted
[I 2024-06-19 18:46:00.162 ServerApp] Starting buffering for 31aa2d3e-3e42-479d-a7df-938909f95eb4:18548042-0aa9-4679-8e14-6ba0e018b25c
[W 2024-06-19 18:46:01.864 ServerApp] Notebook examplefiles/analysis/mbar-Copy1.ipynb is not trusted
[I 2024-06-19 18:46:02.060 ServerApp] Kernel started: 4702132d-1e62-497f-8f39-deda4e61947c
[I 2024-06-19 18:46:04.540 ServerApp] Connecting to kernel 4702132d-1e62-497f-8f39-deda4e61947c.
[I 2024-06-19 18:48:02.044 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[W 2024-06-19 18:48:02.045 ServerApp] Notebook examplefiles/analysis/mbar-Copy1.ipynb is not trusted
[I 2024-06-19 18:50:02.642 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[W 2024-06-19 18:50:02.643 ServerApp] Notebook examplefiles/analysis/mbar-Copy1.ipynb is not trusted
[W 2024-06-19 18:51:08.613 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 18:51:08.897 ServerApp] Connecting to kernel 31aa2d3e-3e42-479d-a7df-938909f95eb4.
[W 2024-06-19 18:51:42.186 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[I 2024-06-19 18:51:42.431 ServerApp] Kernel started: 57dfbc08-35c3-46b2-ad55-4a953e5a9875
[I 2024-06-19 18:51:45.143 ServerApp] Connecting to kernel 57dfbc08-35c3-46b2-ad55-4a953e5a9875.
[I 2024-06-19 18:53:42.316 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[W 2024-06-19 18:53:42.318 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[I 2024-06-19 18:55:42.769 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[W 2024-06-19 18:55:42.769 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[I 2024-06-19 18:57:00.279 ServerApp] Starting buffering for 31aa2d3e-3e42-479d-a7df-938909f95eb4:023abb42-47e7-4715-b42c-ca054bb8e816
[I 2024-06-19 18:57:43.005 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[W 2024-06-19 18:57:43.006 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[I 2024-06-19 18:59:43.302 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[W 2024-06-19 18:59:43.303 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[I 2024-06-19 19:01:43.544 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[W 2024-06-19 19:01:43.545 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[I 2024-06-19 19:03:45.579 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[W 2024-06-19 19:03:45.579 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[I 2024-06-19 19:05:45.782 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[W 2024-06-19 19:05:45.783 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[I 2024-06-19 19:07:51.178 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[W 2024-06-19 19:07:51.179 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[W 2024-06-19 19:08:04.411 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 19:08:04.713 ServerApp] Connecting to kernel 31aa2d3e-3e42-479d-a7df-938909f95eb4.
[I 2024-06-19 19:36:19.785 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[W 2024-06-19 19:36:19.786 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[I 2024-06-19 19:38:20.044 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[W 2024-06-19 19:38:20.045 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[I 2024-06-19 19:40:20.609 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[W 2024-06-19 19:40:20.610 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[I 2024-06-19 19:42:20.827 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[W 2024-06-19 19:42:20.827 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[I 2024-06-19 19:46:21.046 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[W 2024-06-19 19:46:21.047 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[I 2024-06-19 19:48:21.289 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[W 2024-06-19 19:48:21.290 ServerApp] Notebook examplefiles/analysis/oldmbar.ipynb is not trusted
[I 2024-06-19 19:50:19.873 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[W 2024-06-19 19:50:19.874 ServerApp] Notebook examplefiles/analysis/mbar-Copy1.ipynb is not trusted
[I 2024-06-19 19:50:22.357 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[I 2024-06-19 19:52:20.155 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[W 2024-06-19 19:52:20.156 ServerApp] Notebook examplefiles/analysis/mbar-Copy1.ipynb is not trusted
[I 2024-06-19 19:54:20.746 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[W 2024-06-19 19:54:20.746 ServerApp] Notebook examplefiles/analysis/mbar-Copy1.ipynb is not trusted
[I 2024-06-19 19:56:19.865 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[W 2024-06-19 19:56:19.866 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 19:58:20.777 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[W 2024-06-19 19:58:20.778 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 20:00:21.183 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[W 2024-06-19 20:00:21.184 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 20:02:21.473 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[W 2024-06-19 20:02:21.474 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 20:04:22.109 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[W 2024-06-19 20:04:22.110 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 20:06:22.378 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[W 2024-06-19 20:06:22.379 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 20:08:23.362 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[W 2024-06-19 20:08:23.363 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 20:10:23.616 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[W 2024-06-19 20:10:23.616 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 20:12:23.921 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[W 2024-06-19 20:12:23.922 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 20:14:24.322 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[W 2024-06-19 20:14:24.323 ServerApp] Notebook examplefiles/analysis/mbar.ipynb is not trusted
[I 2024-06-19 20:16:24.761 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[I 2024-06-19 20:17:41.699 ServerApp] Starting buffering for 31aa2d3e-3e42-479d-a7df-938909f95eb4:ba5f2d81-bcf1-4cd1-940b-640c664bcfb0
[IPKernelApp] ERROR | Failed to open SQLite history /home/van/.ipython/profile_default/history.sqlite (datatype mismatch).
[IPKernelApp] ERROR | History file was moved to /home/van/.ipython/profile_default/history-corrupt-2024-06-19T20.17.48.388253.sqlite and a new file created.
[I 2024-06-19 20:18:06.018 ServerApp] Kernel restarted: 4702132d-1e62-497f-8f39-deda4e61947c
[I 2024-06-19 20:18:06.050 ServerApp] Starting buffering for 4702132d-1e62-497f-8f39-deda4e61947c:5e866c34-b0a3-4882-9935-4ec0924fa698
[I 2024-06-19 20:18:06.074 ServerApp] Connecting to kernel 4702132d-1e62-497f-8f39-deda4e61947c.
[I 2024-06-19 20:18:06.075 ServerApp] Restoring connection for 4702132d-1e62-497f-8f39-deda4e61947c:5e866c34-b0a3-4882-9935-4ec0924fa698
[W 2024-06-19 20:18:09.750 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x2ab8b03c0b20>
[I 2024-06-19 20:18:23.762 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:21:04.116 LabApp] 302 GET /lab/tree/examplefiles/analysis (@172.18.19.241) 1.05ms
[I 2024-06-19 20:22:24.023 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:24:24.230 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:26:24.402 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:28:24.563 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:30:24.813 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:32:25.729 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:34:25.941 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:36:26.126 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:38:26.322 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:40:26.522 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:42:26.704 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:44:26.937 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:46:27.121 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:48:27.405 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:50:27.586 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:52:27.786 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 20:54:27.982 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 21:00:09.283 ServerApp] Kernel restarted: 4702132d-1e62-497f-8f39-deda4e61947c
[I 2024-06-19 21:00:09.300 ServerApp] Starting buffering for 4702132d-1e62-497f-8f39-deda4e61947c:5e866c34-b0a3-4882-9935-4ec0924fa698
[I 2024-06-19 21:00:09.326 ServerApp] Connecting to kernel 4702132d-1e62-497f-8f39-deda4e61947c.
[I 2024-06-19 21:00:09.326 ServerApp] Restoring connection for 4702132d-1e62-497f-8f39-deda4e61947c:5e866c34-b0a3-4882-9935-4ec0924fa698
[I 2024-06-19 21:00:28.180 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 21:02:28.432 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 21:04:28.622 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 21:06:28.833 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 21:08:29.052 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 21:10:23.841 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[I 2024-06-19 21:10:29.271 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 21:12:29.477 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 21:14:29.738 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 21:16:29.957 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 21:18:30.162 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 21:18:48.407 ServerApp] Connecting to kernel 31aa2d3e-3e42-479d-a7df-938909f95eb4.
[I 2024-06-19 21:20:30.372 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 21:20:48.357 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[I 2024-06-19 21:22:48.560 ServerApp] Saving file at /examplefiles/analysis/mbar.ipynb
[I 2024-06-19 21:45:19.805 ServerApp] Saving file at /examplefiles/analysis/oldmbar.ipynb
[I 2024-06-19 21:53:19.826 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 21:58:02.688 ServerApp] Starting buffering for 31aa2d3e-3e42-479d-a7df-938909f95eb4:328bf6cb-4685-4dcc-b0f6-1a57b39b281c
[I 2024-06-19 21:58:02.689 ServerApp] Starting buffering for 4702132d-1e62-497f-8f39-deda4e61947c:5e866c34-b0a3-4882-9935-4ec0924fa698
[I 2024-06-19 21:58:02.691 ServerApp] Starting buffering for 57dfbc08-35c3-46b2-ad55-4a953e5a9875:9a86e75d-1d1f-4031-9872-6a30dafe6c66
[I 2024-06-19 21:58:02.716 ServerApp] Connecting to kernel 31aa2d3e-3e42-479d-a7df-938909f95eb4.
[I 2024-06-19 21:58:02.717 ServerApp] Restoring connection for 31aa2d3e-3e42-479d-a7df-938909f95eb4:328bf6cb-4685-4dcc-b0f6-1a57b39b281c
[I 2024-06-19 21:58:02.762 ServerApp] Connecting to kernel 4702132d-1e62-497f-8f39-deda4e61947c.
[I 2024-06-19 21:58:02.762 ServerApp] Restoring connection for 4702132d-1e62-497f-8f39-deda4e61947c:5e866c34-b0a3-4882-9935-4ec0924fa698
[I 2024-06-19 21:58:02.831 ServerApp] Connecting to kernel 57dfbc08-35c3-46b2-ad55-4a953e5a9875.
[I 2024-06-19 21:58:02.831 ServerApp] Restoring connection for 57dfbc08-35c3-46b2-ad55-4a953e5a9875:9a86e75d-1d1f-4031-9872-6a30dafe6c66
[W 2024-06-19 21:59:32.717 ServerApp] WebSocket ping timeout after 90001 ms.
[W 2024-06-19 21:59:32.763 ServerApp] WebSocket ping timeout after 90001 ms.
[W 2024-06-19 21:59:32.832 ServerApp] WebSocket ping timeout after 90000 ms.
[I 2024-06-19 21:59:37.722 ServerApp] Starting buffering for 31aa2d3e-3e42-479d-a7df-938909f95eb4:328bf6cb-4685-4dcc-b0f6-1a57b39b281c
[I 2024-06-19 21:59:37.764 ServerApp] Starting buffering for 4702132d-1e62-497f-8f39-deda4e61947c:5e866c34-b0a3-4882-9935-4ec0924fa698
[I 2024-06-19 21:59:37.833 ServerApp] Starting buffering for 57dfbc08-35c3-46b2-ad55-4a953e5a9875:9a86e75d-1d1f-4031-9872-6a30dafe6c66
[I 2024-06-19 22:05:16.749 ServerApp] Connecting to kernel 4702132d-1e62-497f-8f39-deda4e61947c.
[I 2024-06-19 22:05:16.749 ServerApp] Restoring connection for 4702132d-1e62-497f-8f39-deda4e61947c:5e866c34-b0a3-4882-9935-4ec0924fa698
[I 2024-06-19 22:05:17.016 ServerApp] Connecting to kernel 57dfbc08-35c3-46b2-ad55-4a953e5a9875.
[I 2024-06-19 22:05:17.016 ServerApp] Restoring connection for 57dfbc08-35c3-46b2-ad55-4a953e5a9875:9a86e75d-1d1f-4031-9872-6a30dafe6c66
[I 2024-06-19 22:05:17.222 ServerApp] Connecting to kernel 31aa2d3e-3e42-479d-a7df-938909f95eb4.
[I 2024-06-19 22:05:17.222 ServerApp] Restoring connection for 31aa2d3e-3e42-479d-a7df-938909f95eb4:328bf6cb-4685-4dcc-b0f6-1a57b39b281c
[W 2024-06-19 22:07:46.752 ServerApp] WebSocket ping timeout after 119975 ms.
[W 2024-06-19 22:07:47.017 ServerApp] WebSocket ping timeout after 119887 ms.
[W 2024-06-19 22:07:47.224 ServerApp] WebSocket ping timeout after 119918 ms.
[I 2024-06-19 22:07:51.754 ServerApp] Starting buffering for 4702132d-1e62-497f-8f39-deda4e61947c:5e866c34-b0a3-4882-9935-4ec0924fa698
[I 2024-06-19 22:07:52.019 ServerApp] Starting buffering for 57dfbc08-35c3-46b2-ad55-4a953e5a9875:9a86e75d-1d1f-4031-9872-6a30dafe6c66
[I 2024-06-19 22:07:52.227 ServerApp] Starting buffering for 31aa2d3e-3e42-479d-a7df-938909f95eb4:328bf6cb-4685-4dcc-b0f6-1a57b39b281c
[W 2024-06-19 23:02:26.391 LabApp] Could not determine jupyterlab build status without nodejs
[I 2024-06-19 23:02:26.537 ServerApp] Connecting to kernel 31aa2d3e-3e42-479d-a7df-938909f95eb4.
[I 2024-06-19 23:02:26.685 ServerApp] Connecting to kernel 4702132d-1e62-497f-8f39-deda4e61947c.
[I 2024-06-19 23:02:27.048 ServerApp] Starting buffering for 31aa2d3e-3e42-479d-a7df-938909f95eb4:a529c91b-5fb9-4b85-910b-7fa788bfe02d
[I 2024-06-19 23:02:27.049 ServerApp] Starting buffering for 4702132d-1e62-497f-8f39-deda4e61947c:701207b7-e84a-4e62-99ca-b94d0f9925b3
[I 2024-06-19 23:02:27.075 ServerApp] Connecting to kernel 57dfbc08-35c3-46b2-ad55-4a953e5a9875.
[I 2024-06-19 23:02:27.516 ServerApp] Starting buffering for 57dfbc08-35c3-46b2-ad55-4a953e5a9875:f79f1f5e-74a7-40df-8d6f-66064ae9e659
[I 2024-06-19 23:02:28.142 ServerApp] Connecting to kernel 31aa2d3e-3e42-479d-a7df-938909f95eb4.
[I 2024-06-19 23:02:28.363 ServerApp] Connecting to kernel 57dfbc08-35c3-46b2-ad55-4a953e5a9875.
[IPKernelApp] ERROR | Failed to open SQLite history /home/van/.ipython/profile_default/history.sqlite (attempt to write a readonly database).
[IPKernelApp] ERROR | History file was moved to /home/van/.ipython/profile_default/history-corrupt-2024-06-19T23.02.28.398986.sqlite and a new file created.
[I 2024-06-19 23:02:28.528 ServerApp] Connecting to kernel 4702132d-1e62-497f-8f39-deda4e61947c.
[IPKernelApp] ERROR | Failed to open SQLite history /home/van/.ipython/profile_default/history.sqlite (attempt to write a readonly database).
[IPKernelApp] ERROR | History file was moved to /home/van/.ipython/profile_default/history-corrupt-2024-06-19T23.02.28.544641.sqlite and a new file created.
[I 2024-06-19 23:03:46.989 ServerApp] Starting buffering for 31aa2d3e-3e42-479d-a7df-938909f95eb4:68a572ea-4f2e-4e41-9257-09cfdabb74d6
[I 2024-06-19 23:03:47.998 ServerApp] Starting buffering for 57dfbc08-35c3-46b2-ad55-4a953e5a9875:9a95caae-4d8a-4cd2-814f-91c5b7350f34
[I 2024-06-19 23:08:27.884 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[W 2024-06-19 23:09:58.571 ServerApp] delete /examplefiles/analysis/results0
[W 2024-06-19 23:09:58.573 ServerApp] 400 DELETE /api/contents/examplefiles/analysis/results0?1718856598523 (172.18.19.241): send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
[W 2024-06-19 23:09:58.573 ServerApp] wrote error: "send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783'"
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 158, in find_ext_volume_fallback_trash
        check_create(trash_dir)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 96, in check_create
        os.makedirs(dir, 0o700)
      File "/home/van/miniforge3/lib/python3.10/os.py", line 225, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 1027, in delete_file
        send2trash(os_path)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 210, in send2trash
        dest_trash = find_ext_volume_trash(topdir)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 169, in find_ext_volume_trash
        trash_dir = find_ext_volume_fallback_trash(volume_root)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 161, in find_ext_volume_fallback_trash
        raise TrashPermissionError(e.filename)
    send2trash.exceptions.TrashPermissionError: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 335, in delete
        await ensure_async(cm.delete(path))
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/manager.py", line 900, in delete
        await self.delete_file(path)
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 1029, in delete_file
        raise web.HTTPError(400, "send2trash failed: %s" % e) from e
    tornado.web.HTTPError: HTTP 400: Bad Request (send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783')
[W 2024-06-19 23:09:58.576 ServerApp] 400 DELETE /api/contents/examplefiles/analysis/results0?1718856598523 (d92171e8cafe4b9fa3bf748e2511af5c@172.18.19.241) 7.24ms referer=http://127.0.0.1:8988/lab/tree/examplefiles/analysis/mbar-Copy1.ipynb
[W 2024-06-19 23:09:58.602 ServerApp] delete /examplefiles/analysis/results1
[W 2024-06-19 23:09:58.604 ServerApp] 400 DELETE /api/contents/examplefiles/analysis/results1?1718856598562 (172.18.19.241): send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
[W 2024-06-19 23:09:58.605 ServerApp] wrote error: "send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783'"
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 158, in find_ext_volume_fallback_trash
        check_create(trash_dir)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 96, in check_create
        os.makedirs(dir, 0o700)
      File "/home/van/miniforge3/lib/python3.10/os.py", line 225, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 1027, in delete_file
        send2trash(os_path)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 210, in send2trash
        dest_trash = find_ext_volume_trash(topdir)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 169, in find_ext_volume_trash
        trash_dir = find_ext_volume_fallback_trash(volume_root)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 161, in find_ext_volume_fallback_trash
        raise TrashPermissionError(e.filename)
    send2trash.exceptions.TrashPermissionError: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 335, in delete
        await ensure_async(cm.delete(path))
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/manager.py", line 900, in delete
        await self.delete_file(path)
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 1029, in delete_file
        raise web.HTTPError(400, "send2trash failed: %s" % e) from e
    tornado.web.HTTPError: HTTP 400: Bad Request (send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783')
[W 2024-06-19 23:09:58.606 ServerApp] 400 DELETE /api/contents/examplefiles/analysis/results1?1718856598562 (d92171e8cafe4b9fa3bf748e2511af5c@172.18.19.241) 5.43ms referer=http://127.0.0.1:8988/lab/tree/examplefiles/analysis/mbar-Copy1.ipynb
[W 2024-06-19 23:09:58.630 ServerApp] delete /examplefiles/analysis/results2
[W 2024-06-19 23:09:58.632 ServerApp] 400 DELETE /api/contents/examplefiles/analysis/results2?1718856598592 (172.18.19.241): send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
[W 2024-06-19 23:09:58.633 ServerApp] wrote error: "send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783'"
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 158, in find_ext_volume_fallback_trash
        check_create(trash_dir)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 96, in check_create
        os.makedirs(dir, 0o700)
      File "/home/van/miniforge3/lib/python3.10/os.py", line 225, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 1027, in delete_file
        send2trash(os_path)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 210, in send2trash
        dest_trash = find_ext_volume_trash(topdir)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 169, in find_ext_volume_trash
        trash_dir = find_ext_volume_fallback_trash(volume_root)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 161, in find_ext_volume_fallback_trash
        raise TrashPermissionError(e.filename)
    send2trash.exceptions.TrashPermissionError: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 335, in delete
        await ensure_async(cm.delete(path))
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/manager.py", line 900, in delete
        await self.delete_file(path)
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 1029, in delete_file
        raise web.HTTPError(400, "send2trash failed: %s" % e) from e
    tornado.web.HTTPError: HTTP 400: Bad Request (send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783')
[W 2024-06-19 23:09:58.634 ServerApp] 400 DELETE /api/contents/examplefiles/analysis/results2?1718856598592 (d92171e8cafe4b9fa3bf748e2511af5c@172.18.19.241) 5.06ms referer=http://127.0.0.1:8988/lab/tree/examplefiles/analysis/mbar-Copy1.ipynb
[W 2024-06-19 23:09:58.636 ServerApp] delete /examplefiles/analysis/results5
[W 2024-06-19 23:09:58.638 ServerApp] 400 DELETE /api/contents/examplefiles/analysis/results5?1718856598593 (172.18.19.241): send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
[W 2024-06-19 23:09:58.639 ServerApp] wrote error: "send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783'"
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 158, in find_ext_volume_fallback_trash
        check_create(trash_dir)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 96, in check_create
        os.makedirs(dir, 0o700)
      File "/home/van/miniforge3/lib/python3.10/os.py", line 225, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 1027, in delete_file
        send2trash(os_path)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 210, in send2trash
        dest_trash = find_ext_volume_trash(topdir)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 169, in find_ext_volume_trash
        trash_dir = find_ext_volume_fallback_trash(volume_root)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 161, in find_ext_volume_fallback_trash
        raise TrashPermissionError(e.filename)
    send2trash.exceptions.TrashPermissionError: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 335, in delete
        await ensure_async(cm.delete(path))
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/manager.py", line 900, in delete
        await self.delete_file(path)
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 1029, in delete_file
        raise web.HTTPError(400, "send2trash failed: %s" % e) from e
    tornado.web.HTTPError: HTTP 400: Bad Request (send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783')
[W 2024-06-19 23:09:58.640 ServerApp] 400 DELETE /api/contents/examplefiles/analysis/results5?1718856598593 (d92171e8cafe4b9fa3bf748e2511af5c@172.18.19.241) 5.01ms referer=http://127.0.0.1:8988/lab/tree/examplefiles/analysis/mbar-Copy1.ipynb
[W 2024-06-19 23:09:58.643 ServerApp] delete /examplefiles/analysis/results3
[W 2024-06-19 23:09:58.645 ServerApp] 400 DELETE /api/contents/examplefiles/analysis/results3?1718856598599 (172.18.19.241): send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
[W 2024-06-19 23:09:58.646 ServerApp] wrote error: "send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783'"
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 158, in find_ext_volume_fallback_trash
        check_create(trash_dir)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 96, in check_create
        os.makedirs(dir, 0o700)
      File "/home/van/miniforge3/lib/python3.10/os.py", line 225, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 1027, in delete_file
        send2trash(os_path)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 210, in send2trash
        dest_trash = find_ext_volume_trash(topdir)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 169, in find_ext_volume_trash
        trash_dir = find_ext_volume_fallback_trash(volume_root)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 161, in find_ext_volume_fallback_trash
        raise TrashPermissionError(e.filename)
    send2trash.exceptions.TrashPermissionError: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 335, in delete
        await ensure_async(cm.delete(path))
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/manager.py", line 900, in delete
        await self.delete_file(path)
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 1029, in delete_file
        raise web.HTTPError(400, "send2trash failed: %s" % e) from e
    tornado.web.HTTPError: HTTP 400: Bad Request (send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783')
[W 2024-06-19 23:09:58.647 ServerApp] 400 DELETE /api/contents/examplefiles/analysis/results3?1718856598599 (d92171e8cafe4b9fa3bf748e2511af5c@172.18.19.241) 5.48ms referer=http://127.0.0.1:8988/lab/tree/examplefiles/analysis/mbar-Copy1.ipynb
[W 2024-06-19 23:09:58.650 ServerApp] delete /examplefiles/analysis/results4
[W 2024-06-19 23:09:58.652 ServerApp] 400 DELETE /api/contents/examplefiles/analysis/results4?1718856598610 (172.18.19.241): send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
[W 2024-06-19 23:09:58.653 ServerApp] wrote error: "send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783'"
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 158, in find_ext_volume_fallback_trash
        check_create(trash_dir)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 96, in check_create
        os.makedirs(dir, 0o700)
      File "/home/van/miniforge3/lib/python3.10/os.py", line 225, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 1027, in delete_file
        send2trash(os_path)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 210, in send2trash
        dest_trash = find_ext_volume_trash(topdir)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 169, in find_ext_volume_trash
        trash_dir = find_ext_volume_fallback_trash(volume_root)
      File "/home/van/miniforge3/lib/python3.10/site-packages/send2trash/plat_other.py", line 161, in find_ext_volume_fallback_trash
        raise TrashPermissionError(e.filename)
    send2trash.exceptions.TrashPermissionError: [Errno 13] Permission denied: b'/scratch/.Trash-2783'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/van/miniforge3/lib/python3.10/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 335, in delete
        await ensure_async(cm.delete(path))
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/manager.py", line 900, in delete
        await self.delete_file(path)
      File "/home/van/miniforge3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 1029, in delete_file
        raise web.HTTPError(400, "send2trash failed: %s" % e) from e
    tornado.web.HTTPError: HTTP 400: Bad Request (send2trash failed: [Errno 13] Permission denied: b'/scratch/.Trash-2783')
[W 2024-06-19 23:09:58.654 ServerApp] 400 DELETE /api/contents/examplefiles/analysis/results4?1718856598610 (d92171e8cafe4b9fa3bf748e2511af5c@172.18.19.241) 5.51ms referer=http://127.0.0.1:8988/lab/tree/examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 23:10:14.205 ServerApp] Creating new notebook in /examplefiles/analysis
[I 2024-06-19 23:10:14.794 ServerApp] Kernel started: d1926398-ebc8-4e16-bc66-e48203b0672c
[I 2024-06-19 23:10:17.651 ServerApp] Connecting to kernel d1926398-ebc8-4e16-bc66-e48203b0672c.
[I 2024-06-19 23:10:17.783 ServerApp] Connecting to kernel d1926398-ebc8-4e16-bc66-e48203b0672c.
[I 2024-06-19 23:10:17.932 ServerApp] Connecting to kernel d1926398-ebc8-4e16-bc66-e48203b0672c.
[I 2024-06-19 23:12:14.723 ServerApp] Saving file at /examplefiles/analysis/Untitled.ipynb
[I 2024-06-19 23:15:10.110 ServerApp] Creating new notebook in /Scripts/bin
[I 2024-06-19 23:15:10.708 ServerApp] Kernel started: 9e486993-ff01-4cd5-83ba-2b1ecf89f9cd
[I 2024-06-19 23:15:12.544 ServerApp] Connecting to kernel 9e486993-ff01-4cd5-83ba-2b1ecf89f9cd.
[I 2024-06-19 23:15:17.258 ServerApp] Starting buffering for d1926398-ebc8-4e16-bc66-e48203b0672c:ff53aa97-1936-4c95-b7c0-e5b0d7c72f50
[I 2024-06-19 23:15:46.648 ServerApp] Creating new file in /Scripts/bin
[I 2024-06-19 23:16:28.333 ServerApp] Saving file at /examplefiles/analysis/mbar-Copy1.ipynb
[I 2024-06-19 23:17:10.600 ServerApp] Saving file at /Scripts/bin/Untitled.ipynb
[I 2024-06-19 23:18:53.500 ServerApp] Saving file at /Scripts/bin/mbar.py
[I 2024-06-19 23:18:54.881 ServerApp] Saving file at /Scripts/bin/mbar.py
[I 2024-06-19 23:19:10.923 ServerApp] Saving file at /Scripts/bin/Untitled.ipynb
[I 2024-06-19 23:19:40.064 ServerApp] Kernel started: e9d4efcc-6a98-4811-b99d-77c3d324dca4
[I 2024-06-19 23:19:40.066 ServerApp] Kernel shutdown: 9e486993-ff01-4cd5-83ba-2b1ecf89f9cd
[I 2024-06-19 23:19:54.964 ServerApp] Connecting to kernel e9d4efcc-6a98-4811-b99d-77c3d324dca4.
[I 2024-06-19 23:20:53.822 ServerApp] Saving file at /Scripts/bin/mbar.py
[I 2024-06-19 23:21:11.318 ServerApp] Saving file at /Scripts/bin/Untitled.ipynb
[I 2024-06-19 23:23:11.704 ServerApp] Saving file at /Scripts/bin/Untitled.ipynb
[I 2024-06-19 23:25:12.042 ServerApp] Saving file at /Scripts/bin/Untitled.ipynb
[I 2024-06-19 23:27:12.511 ServerApp] Saving file at /Scripts/bin/Untitled.ipynb
[I 2024-06-19 23:29:13.392 ServerApp] Saving file at /Scripts/bin/Untitled.ipynb
[I 2024-06-19 23:31:13.740 ServerApp] Saving file at /Scripts/bin/Untitled.ipynb
[I 2024-06-19 23:33:15.131 ServerApp] Saving file at /Scripts/bin/Untitled.ipynb
[I 2024-06-19 23:35:15.463 ServerApp] Saving file at /Scripts/bin/Untitled.ipynb
[I 2024-06-19 23:37:15.791 ServerApp] Saving file at /Scripts/bin/Untitled.ipynb
[I 2024-06-19 23:41:16.211 ServerApp] Saving file at /Scripts/bin/Untitled.ipynb
[I 2024-06-19 23:43:44.197 ServerApp] Saving file at /Scripts/bin/mbar.py
[I 2024-06-19 23:43:55.880 ServerApp] Saving file at /Scripts/bin/Untitled.ipynb
[I 2024-06-19 23:43:58.537 ServerApp] Starting buffering for e9d4efcc-6a98-4811-b99d-77c3d324dca4:2c581c29-90d0-43bc-86fd-a44b638068ad
[I 2024-06-19 23:44:02.797 ServerApp] Starting buffering for 4702132d-1e62-497f-8f39-deda4e61947c:6f880219-cae8-4694-a26e-e530b7c34128
[W 2024-06-19 23:44:12.429 LabApp] Could not determine jupyterlab build status without nodejs
[I 2024-06-19 23:44:12.553 ServerApp] Connecting to kernel 31aa2d3e-3e42-479d-a7df-938909f95eb4.
[I 2024-06-19 23:44:12.752 ServerApp] Starting buffering for 31aa2d3e-3e42-479d-a7df-938909f95eb4:10f076ac-41d5-4a7a-aa5b-8250b07c3bd1
[I 2024-06-19 23:44:12.753 ServerApp] Connecting to kernel 4702132d-1e62-497f-8f39-deda4e61947c.
[I 2024-06-19 23:44:12.911 ServerApp] Connecting to kernel 57dfbc08-35c3-46b2-ad55-4a953e5a9875.
[I 2024-06-19 23:44:12.957 ServerApp] Starting buffering for 4702132d-1e62-497f-8f39-deda4e61947c:d750e45d-8d1e-4d80-b5f5-c00a9743f116
[I 2024-06-19 23:44:13.101 ServerApp] Starting buffering for 57dfbc08-35c3-46b2-ad55-4a953e5a9875:12d9ec9f-f090-4de4-a7e2-60e36e945034
[I 2024-06-19 23:44:13.105 ServerApp] Connecting to kernel d1926398-ebc8-4e16-bc66-e48203b0672c.
[I 2024-06-19 23:44:13.264 ServerApp] Starting buffering for d1926398-ebc8-4e16-bc66-e48203b0672c:76076671-1175-483d-bb02-cc426ba3a47f
[I 2024-06-19 23:44:13.268 ServerApp] Connecting to kernel e9d4efcc-6a98-4811-b99d-77c3d324dca4.
[I 2024-06-19 23:44:13.423 ServerApp] Starting buffering for e9d4efcc-6a98-4811-b99d-77c3d324dca4:aadfd77b-6f45-4df0-9c7d-af42f8fa75de
[I 2024-06-19 23:44:43.897 ServerApp] New terminal with automatic name: 1
[I 2024-06-19 23:45:31.604 ServerApp] Kernel started: 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0
[I 2024-06-19 23:45:34.307 ServerApp] Connecting to kernel 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0.
[I 2024-06-19 23:47:31.462 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-19 23:49:31.826 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-19 23:51:32.249 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-19 23:53:34.231 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-19 23:55:34.634 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-19 23:57:34.948 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-19 23:59:35.259 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:01:35.893 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:03:36.344 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:05:36.744 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:07:39.798 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:09:40.203 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:11:40.548 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:13:41.079 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:15:41.872 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:17:42.236 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:19:42.550 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:21:43.034 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:23:43.524 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:25:43.835 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:27:44.509 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:29:44.885 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:31:11.169 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:33:11.558 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:35:11.998 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:37:12.566 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:39:12.920 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:41:13.423 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:43:14.054 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:45:14.665 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:47:15.079 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:49:16.082 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:51:16.487 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:53:16.823 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:55:17.232 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:57:17.635 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 00:59:18.192 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:01:18.634 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:03:19.042 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:05:19.851 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:07:20.514 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:09:21.233 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:11:21.877 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:13:22.239 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:15:22.613 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:17:22.952 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:19:23.312 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:21:23.662 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:23:24.106 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:25:24.466 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:27:24.823 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:29:25.178 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:31:25.552 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:33:25.879 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:35:26.728 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:37:27.275 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:39:27.624 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:41:29.120 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:43:29.467 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:45:30.002 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:47:30.371 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:49:30.707 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:51:31.085 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:53:31.591 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:55:31.948 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:57:32.311 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 01:59:32.695 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:01:33.042 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:03:34.164 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:04:58.300 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:06:23.081 ServerApp] Kernel restarted: 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0
[I 2024-06-20 02:06:23.219 ServerApp] Starting buffering for 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0:8f9f297e-a120-4bb1-936e-622a7511992c
[I 2024-06-20 02:06:23.345 ServerApp] Connecting to kernel 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0.
[I 2024-06-20 02:06:23.345 ServerApp] Restoring connection for 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0:8f9f297e-a120-4bb1-936e-622a7511992c
[I 2024-06-20 02:06:33.818 ServerApp] Creating new file in /Scripts/mbar
[I 2024-06-20 02:06:58.858 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[W 2024-06-20 02:07:23.083 ServerApp] Timeout waiting for kernel_info_reply: 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0
Future exception was never retrieved
future: <Future finished exception=TimeoutError('Timeout waiting for restart')>
TimeoutError: Timeout waiting for restart
[I 2024-06-20 02:08:34.221 ServerApp] Saving file at /Scripts/mbar/untitled.md
[I 2024-06-20 02:08:59.252 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:10:59.703 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:13:00.135 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:15:01.026 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:17:03.546 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:19:04.219 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:21:05.113 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:23:05.552 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:25:10.301 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:27:10.805 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:27:49.761 ServerApp] Kernel restarted: 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0
[I 2024-06-20 02:27:50.062 ServerApp] Starting buffering for 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0:8f9f297e-a120-4bb1-936e-622a7511992c
[I 2024-06-20 02:27:50.139 ServerApp] Connecting to kernel 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0.
[I 2024-06-20 02:27:50.139 ServerApp] Restoring connection for 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0:8f9f297e-a120-4bb1-936e-622a7511992c
[I 2024-06-20 02:29:11.189 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:30:07.665 ServerApp] Starting buffering for 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0:8f9f297e-a120-4bb1-936e-622a7511992c
[I 2024-06-20 02:30:10.991 ServerApp] Connecting to kernel 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0.
[I 2024-06-20 02:31:53.879 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:31:55.000 ServerApp] Starting buffering for 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0:45b9bab6-38f0-4ae2-b3a9-20d728f50740
[I 2024-06-20 02:32:01.995 ServerApp] Connecting to kernel 446d4ddd-2f2d-4aa1-a9c5-4736a74bc6a0.
[I 2024-06-20 02:34:01.876 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:36:03.247 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:38:03.850 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:40:04.244 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:42:04.672 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:44:05.486 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:46:06.348 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:48:10.582 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:50:11.564 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:52:12.125 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
[I 2024-06-20 02:54:12.648 ServerApp] Saving file at /Scripts/mbar/workflow.ipynb
slurmstepd: error: *** JOB 4982029 ON himem04 CANCELLED AT 2024-06-20T02:59:18 ***
